services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      MEMORY: 7G
      MOD_PLATFORM: MODRINTH
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
      MODRINTH_MODPACK: wing-server # this installs the latest version of Adrenaserver, you can also use a specific MR link to a version
      MODRINTH_PROJECTS: ledger, fabric-language-kotlin, image2map # comma separated list of extra mods
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data